import { Product } from '@/types';
export const products: Product[] = [
  {
    id: 'Product 1',
    src: '/images/jggery6.png',
    content: 'Natural Jaggery (Gur)',
    summary: 'Premium chemical-free jaggery made from fresh sugarcane juice using traditional methods. Rich in minerals, deep in flavor — the purest form of natural sweetness.',
    price: 64,
    priceLabel: 'Rs 64/kg',
    category: 'Solid Jaggery',
    hsCode : "HS CODE : 17011410",
    emoji: '🟫',
    benefits: ['Rich in iron and minerals', 'Chemical-free and unrefined', 'Natural energy booster', 'Boosts immunity with antioxidants'],
    unit: 'per kg',
    longDescription: 'Our Natural Jaggery is crafted using time-honored methods passed down through generations. Sourced directly from sugarcane farms in Maharashtra, every block is slow-boiled in iron vessels to preserve its natural golden color and rich mineral content. Free from any chemicals, preservatives, or artificial additives.',
    origin: 'Maharashtra, India',
    weight: '1 kg',
    inStock: true,
  },
  {
    id: 'Product 2',
    src: '/images/jggery6.png',
    content: 'Regular Jaggery (Gur)',
    summary: 'Classic jaggery made from sugarcane juice — a wholesome, everyday natural sweetener perfect for tea, sweets, and traditional cooking.',
    price: 50,
    priceLabel: 'Rs 50/kg',
    category: 'Solid Jaggery',
    hsCode : "HS CODE : 17011410",
    emoji: '🟫',
    benefits: ['Natural sweetener', 'Good source of iron and calcium', 'Supports digestion', 'Affordable daily-use sweetener'],
    unit: 'per kg',
    longDescription: 'Our Regular Jaggery offers the familiar taste and goodness of traditional Indian jaggery at an accessible price. Made from fresh sugarcane juice and processed without harmful chemicals, it is ideal for everyday use in households, tea stalls, and food businesses.',
    origin: 'Maharashtra, India',
    weight: '1 kg',
    inStock: true,
  },
  {
    id: 'Product 3',
    src: '/images/Jaggery-Powder.png',
    content: 'Natural Jaggery Powder',
    summary: 'Finely ground from premium natural jaggery — retains all minerals and nutrients. Easy to dissolve, ideal for tea, coffee, desserts, and health-conscious cooking.',
    price: 69,
    priceLabel: 'Rs 69/kg',
    category: 'Powdered Jaggery',
    hsCode : "HS CODE : 17011420",
    emoji: '🟤',
    benefits: ['Instant dissolving', 'Full nutrition of natural jaggery', 'No added preservatives or fillers', 'Mineral rich'],
    unit: 'per kg',
    longDescription: 'Natural Jaggery Powder is stone-ground from our premium natural jaggery blocks, preserving all the trace minerals and antioxidants. Perfect for tea, coffee, desserts, and everyday cooking.',
    origin: 'Maharashtra, India',
    weight: '1 kg',
    inStock: true,
  },
  {
    id: 'Product 4',
    src: '/images/Jaggery-Powder.png',
    content: 'Regular Jaggery Powder',
    summary: 'Convenient powdered jaggery for everyday use. Dissolves quickly in hot and cold drinks, great for traditional recipes, sweets, and snacks.',
    price: 53,
    priceLabel: 'Rs 53/kg',
    category: 'Powdered Jaggery',
    hsCode : "HS CODE : 17011420",
    emoji: '🟤',
    benefits: ['Easy to measure and use', 'Dissolves quickly', 'Natural sweetener', 'Cost-effective bulk option'],
    unit: 'per kg',
    longDescription: 'Regular Jaggery Powder brings the ease and convenience of powdered sweetener with the wholesome goodness of jaggery. An everyday essential for households and food businesses alike.',
    origin: 'Maharashtra, India',
    weight: '1 kg',
    inStock: true,
  },
  {
    id: 'Product 5',
    src: '/images/kakvi.avif',
    content: 'Natural Liquid Jaggery (Kakvi)',
    summary: 'Traditional liquid jaggery made from pure sugarcane juice. Rich, smooth, and deeply flavored — perfect for chapati, milk, or Ayurvedic preparations.',
    price: 130,
    priceLabel: 'Rs 130/liter',
    category: 'Liquid Jaggery',
    hsCode : "HS CODE : 170290",
    emoji: '🫙',
    benefits: ['Highest mineral concentration', 'Ready to use', 'Traditional Maharashtrian recipe', 'No preservatives or thickeners'],
    unit: 'per liter',
    longDescription: 'Natural Liquid Jaggery, known locally as Kakvi, is the rich amber nectar extracted during the natural jaggery-making process. With its deep molasses-like sweetness and dense mineral content, it is a prized ingredient in traditional Indian households and Ayurvedic kitchens.',
    origin: 'Maharashtra, India',
    weight: '1 liter',
    inStock: true,
  },
  {
    id: 'Product 6',
    src: '/images/jggery6.png',
    content: 'Other Agro Products',
    summary: 'We are expanding our range of premium agro products. Stay tuned for new additions from the farms of Maharashtra — coming soon.',
    price: 0,
    priceLabel: 'Coming Soon',
    category: 'Agro Products',
    hsCode : "HS CODE : ",
    emoji: '🌾',
    benefits: ['Directly sourced from farmers', 'Export-ready quality', 'Sustainably grown', 'Custom sourcing available'],
    unit: 'per kg',
    longDescription: 'Namaste Global is continuously working to bring more high-quality agro products to market. Contact us to inquire about specific commodities or bulk sourcing requirements.',
    origin: 'Maharashtra, India',
    weight: 'TBD',
    inStock: false,
  },
];
export const getProductById = (id: string) =>
  products.find((p) => p.id === id) ?? null;
export const data = products;